import { writeFile, readFile, copyFile, access } from 'fs/promises';
import { homedir } from 'os';
import { join } from 'path';
import type { SlimConfig, PresetConfig, CouncilConfig, GeneratorOptions } from '../types.js';

export async function writeConfig(
  presets: Record<string, PresetConfig>,
  councilConfig: CouncilConfig,
  options: GeneratorOptions
): Promise<void> {
  const configPath = join(homedir(), '.config/opencode/oh-my-opencode-slim.jsonc');
  
  // Backup existing config
  try {
    await access(configPath);
    if (!options.reset) {
      const backupPath = `${configPath}.backup.${Date.now()}`;
      await copyFile(configPath, backupPath);
      console.log(`  Backed up existing config to: ${backupPath}`);
    }
  } catch {
    // File doesn't exist, no backup needed
  }
  
  // Build config object
  const config: SlimConfig = {
    $schema: 'https://unpkg.com/oh-my-opencode-slim@latest/oh-my-opencode-slim.schema.json',
    preset: options.preset || 'default',
    presets,
    council: councilConfig,
    fallback: {
      enabled: true,
      timeoutMs: 15000,
      retryDelayMs: 500,
      chains: generateFallbackChains(presets),
    },
  };
  
  // Add header comments
  const timestamp = new Date().toISOString();
  const presetNames = Object.keys(presets).join(', ');
  const header = 
    `// Auto-generated by generate-slim-config on ${timestamp}\n` +
    `// Available presets: ${presetNames}\n` +
    `// To switch presets: change "preset" field or set OH_MY_OPENCODE_SLIM_PRESET env var\n\n`;
  
  const jsonContent = JSON.stringify(config, null, 2);
  
  if (options.dryRun) {
    console.log('\n[DRY RUN] Would write to:', configPath);
    console.log('\n' + header + jsonContent);
    return;
  }
  
  // Write to file
  await writeFile(configPath, header + jsonContent, 'utf8');
  
  console.log(`\n  ✓ Configuration written to: ${configPath}`);
  console.log(`  Active preset: ${config.preset}`);
  console.log(`  Available presets: ${presetNames}`);
}

function generateFallbackChains(presets: Record<string, PresetConfig>): Record<string, string[]> {
  const chains: Record<string, string[]> = {};
  
  // Use default preset for fallback chains
  const defaultPreset = presets.default || Object.values(presets)[0];
  if (!defaultPreset) return chains;
  
  for (const [agentName, agentConfig] of Object.entries(defaultPreset)) {
    const model = Array.isArray(agentConfig.model) 
      ? agentConfig.model[0]
      : agentConfig.model;
    
    // Collect all models for this agent across presets
    const allModels = new Set<string>();
    allModels.add(model);
    
    for (const preset of Object.values(presets)) {
      const presetAgentConfig = preset[agentName];
      if (presetAgentConfig) {
        const presetModel = Array.isArray(presetAgentConfig.model)
          ? presetAgentConfig.model[0]
          : presetAgentConfig.model;
        allModels.add(presetModel);
      }
    }
    
    chains[agentName] = Array.from(allModels);
  }
  
  return chains;
}

export function printSummary(
  presets: Record<string, PresetConfig>,
  providers: string[],
  verbose: boolean
): void {
  console.log('\n=== Configuration Summary ===\n');
  console.log(`Providers detected: ${providers.join(', ')}`);
  console.log(`Presets generated: ${Object.keys(presets).length}`);
  
  if (verbose) {
    console.log('\n--- Agent Model Assignments (default preset) ---');
    const defaultPreset = presets.default || Object.values(presets)[0];
    for (const [agentName, config] of Object.entries(defaultPreset)) {
      const model = Array.isArray(config.model) ? config.model[0] : config.model;
      console.log(`  ${agentName.padEnd(15)} → ${model}`);
    }
    
    console.log('\n--- All Presets ---');
    for (const presetName of Object.keys(presets)) {
      console.log(`  - ${presetName}`);
    }
  }
}
